version: '3.8'
services:
  nginx:
    build: ./nginx  # Construir la imagen desde el Dockerfile en la carpeta nginx/
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge