services:
  nginx:
    build:
      context: ./nginx  # El contexto de la construcci칩n, que ser치 el directorio ./nginx
      dockerfile: Dockerfile  # El Dockerfile dentro de ese directorio
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app-network

  mariadb:
    build:
      context: ./mariadb  # El contexto de la construcci칩n, que ser치 el directorio ./mariadb
      dockerfile: Dockerfile  # El Dockerfile dentro de ese directorio
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
