# Usamos la imagen base de MariaDB
FROM mariadb:latest

# Establecer variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Exponer el puerto de MariaDB
EXPOSE 3306
