# Usar la imagen oficial de MariaDB como base
FROM mariadb:latest

# Variables de entorno para la configuración de MariaDB
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Exponer el puerto 3306
EXPOSE 3306

