name: CI/CD Pipeline for Nginx-MariaDB

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nginx image
        run: |
          docker-compose -f docker-compose.yml build nginx  # Construir la imagen de Nginx
          docker-compose -f docker-compose.yml push nginx  # Subir la imagen de Nginx a DockerHub

      - name: Build and push MariaDB image
        run: |
          docker-compose -f docker-compose.yml build mariadb  # Construir la imagen de MariaDB
          docker-compose -f docker-compose.yml push mariadb  # Subir la imagen de MariaDB a DockerHub

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no root@116.203.102.137 "cd /root/nginx-mariadb && git pull && docker-compose up -d"
