name: CI/CD Pipeline for Nginx-MariaDB

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-mariadb-nginx:latest ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-mariadb-nginx:latest

      - name: Build and push MariaDB image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-mariadb-mariadb:latest ./mariadb
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-mariadb-mariadb:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configurar SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Conectar al VPS y desplegar
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@116.203.102.137 <<EOF
            # Clonar el repositorio si no existe
            if [ ! -d "/root/nginx-mariadb" ]; then
              git clone https://github.com/TU_USUARIO/nginx-mariadb.git /root/nginx-mariadb
            else
              cd /root/nginx-mariadb
              git pull origin main
            fi
            
            # Descargar las imágenes actualizadas de Docker Hub
            cd /root/nginx-mariadb
            docker-compose pull
            
            # Reiniciar los contenedores con las nuevas imágenes
            docker-compose up -d --remove-orphans
EOF
