name: CI/CD Pipeline for Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-nginx:latest ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-nginx:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Configurar SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Conectar al VPS y desplegar. Introduce la IP de tu máquina
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@<IP> <<EOF
          # Clonar el repositorio si no existe
          if [ ! -d "/root/nginx" ]; then
            git clone https://github.com/jose404notfound/nginx.git /root/nginx
          else
            cd /root/nginx
            git pull origin main
          fi
          
          # Descargar las imágenes actualizadas de Docker Hub
          cd /root/nginx
          docker pull ${DOCKER_USERNAME}/nginx-nginx:latest
          
          # Reiniciar los contenedores con la imagen nueva
          docker compose up -d --remove-orphans
          EOF
